### ISSUE TITLE
Update to Python 3.9

### ISSUE THREAD

**Issue by paulocoutinhox** [vittorio-nardone/selenium-chromium-lambda#9]
Hi,

Can you update to Python 3.9?

Thanks.

**Comment by paulocoutinhox** [comment]
Im getting this error:

```
[ERROR] WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 127

Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 80, in lambda_handler
    driver = webdriver.Chrome(chrome_options=chrome_options)
  File "/opt/python/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/opt/python/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/opt/python/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
```

**Comment by selected-pixel-jameson** [comment]
Would also love some direction on this.

**Comment by dilipkhemani** [comment]
was anyone able to resolve this. I am getting the same error on python 3.12
